from .extract_schools_data_from_weduc import extract_schools_data_from_weduc
from .extract_timetable_from_weduc_and_add_to_student_config import (
    extract_timetable_from_weduc_and_add_to_student_config,
)
from .launch_browser_and_log_in import launch_browser_and_log_in
